local p = require("lush_theme._primitive").hsl

-- design system: semantic token
return {
	_keyword = { fg = p.mono25 },
	_preproc00 = { fg = p.mono15, gui = "italic" },
	_preproc01 = { fg = p.mono19, gui = "italic" },
	_preproc02 = { fg = p.mono23, gui = "italic" },
	_operator = { fg = p.mono21 },
	_special00 = { fg = p.mono15 },
	_special01 = { fg = p.mono19 },
	_special02 = { fg = p.mono21 },
	_constant = { fg = p.accDim05 },
	_string = { fg = p.mono15 },
	_boolean = { fg = p.mono17 },
	_number = { fg = p.mono17 },
	_variable = { fg = p.mono17 },
	_variable_builtin = { fg = p.acc07, gui = "italic" },
	_variable_member = { fg = p.mono20 },
	_namespace = { fg = p.mono23, gui = "underline" },
	_type = { fg = p.mono23 },
	_interface = { fg = p.mono23 },
	_class = { fg = p.mono17 },
	_property = { fg = p.accDim02, gui = "italic" },
	_function = { fg = p.mono22 },
	_parameter = { fg = p.mono17, gui = "bold underline" },
	_method = { fg = p.mono22, gui = "italic" },
	_block = { fg = p.mono19, gui = "bold" },
	_error = { fg = p.red00, gui = "bold" },
	_coroutine = { fg = p.acc07 },
	_event = { fg = p.accDim02, gui = "underline" },
	_tag = { fg = p.mono25 },
	_attribute = { fg = p.mono14 },
	_none = { fg = p.mono10 },
	_regexp = { fg = p.mono15 },
	_comment = { fg = p.mono12, gui = "italic" },
	_md_h1 = { fg = p.mono25, gui = "bold underline" },
	_md_h2 = { fg = p.mono24, gui = "bold underline" },
	_md_h3 = { fg = p.mono23, gui = "bold" },
	_md_h4 = { fg = p.mono22 },
	_md_h5 = { fg = p.mono21 },
	_md_h6 = { fg = p.mono21, gui = "italic" },
}
